require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - test/**/*
    - bigbang-rails.gemspec

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
